### ISSUE TITLE
fish shell redirection problem

### ISSUE THREAD

**Issue by muralikodali** [ericlay/fuzzy-pkg-finder#2]
It is a convenient script for package management.
I have substituted `yay` with `paru`

I am able to install and remove packages without problem.
but, fzf preview pane is showing error as shown below.

![screenshot_20210709202144](https://user-images.githubusercontent.com/11482766/125097291-9c5dcd80-e0f3-11eb-8634-00e46272e868.png)

it is showing error as fish shell piping output (redirection).

how can this shell redirection error can be avoided ?

**Comment by ericlay** [comment]
Glad it was easy substitute for you! 

Fish shell handles some things differently. That style of redirect is a bash-ism. For fish the preview commands will work if edited as below:
`'cat (paru -Si {1} | psub) (pacman -Ql {1} 2>/dev/null | awk "{print \$2}" | psub)'`

Fish is a popular shell. I think the answer would be to check default shell and choose which version on install. Which means refactoring the pkgbuild and uploading the fish script file. 

In the mean time, here's a drop in replacement that should work, https://ghostbin.com/paste/t3BW9

**Comment by muralikodali** [comment]
Thanks

your [drop in replacement](https://ghostbin.com/paste/t3BW9) is working without errors.

**Comment by ericlay** [comment]
@muralikodali 

I've simply added a second script that handles the redirects for fish shells as `fpff`, same as the drop in replacement. If you installed from AUR the changes will be picked up and the new command will be available to you.
