### ISSUE TITLE
Description shown next to the package 

### ISSUE THREAD

**Issue by ShalokShalom** [ericlay/fuzzy-pkg-finder#8]
Hi there :)

I just installed your script - on Garuda - and wonder why there is the description added next to the package name.

![Screenshot_20230919_163930](https://github.com/ericlay/fuzzy-pkg-finder/assets/6344099/59ed1f15-3297-44a2-902e-b35547170f48)

This is not the case in your screenshot, and I would prefer it that way.

**Comment by ericlay** [comment]
It was an update to better meet the preferences of myself and others. See this [issue](https://github.com/ericlay/fuzzy-pkg-finder/issues/5)

You could choose an earlier commit and fork from there or try another fzf pacman/aur wrapper script that better suites your needs.
https://github.com/sheepla/fzpac
https://github.com/ConnerWill/yayfzf
https://github.com/DanielFGray/fzf-scripts/blob/master/pkgsearch

**Comment by ShalokShalom** [comment]
Why not making that configurable?

**Comment by ericlay** [comment]
I'm fairly happy with it this way. IF you wanted to submit a PR that allows for that it could be worked out. 

For older version that might meet your preferences:
remove new version `sudo pacman -Rsn fuzzy-pkg-finder`
and files `sudo rm -rf /usr/bin/fpf` just like to double check
clone the repository locally `cd ~ && git clone https://github.com/ericlay/fuzzy-pkg-finder.git`
cd into repository `cd fuzzy-pkg-finder`
Use `git checkout a58b3b0` to revert to last commit functioning that way
install this version `make install -si`

From there you are on your own. I would again suggest forking from that commit and maintaining that.
